apiVersion: io.platform.fastboot/v1alpha1
kind: Platform
metadata:
  name: {{ .Values.platform.name }}
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.platform.name }}
  stage: {{ .Values.platform.stage }}
  version: {{ .Values.platform.version }}

  defaults:
    database:
      storageClass: {{ .Values.platform.defaults.database.storageClass }}
      externalAccess: {{ .Values.platform.defaults.database.externalAccess }}
      sizes:
      {{ toYaml .Values.platform.defaults.database.sizes | nindent 8 }}

  services:
    databases:
    {{- if .Values.platformServices.databases }}
    {{- range .Values.platformServices.databases }}
      - databaseName: {{ .databaseName }}
        type: {{ .type }}
        version: {{ .version | quote }}
        {{- if hasKey . "port" }}
        port: {{ .port }}
        {{- end }}
        {{- if hasKey . "size" }}
        size: {{ .size }}
        {{- end }}
        {{- if hasKey . "storageClass" }}
        storageClass: {{ .storageClass }}
        {{- else }}
        storageClass: {{ $.Values.platform.defaults.database.storageClass }}
        {{- end }}
        {{- if hasKey . "externalAccess" }}
        externalAccess: {{ .externalAccess }}
        {{- else }}
        externalAccess: {{ $.Values.platform.defaults.database.externalAccess }}
        {{- end }}
    {{- end }}
    {{- else }}
      []
    {{- end }}