apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastboot-operator-sa
  namespace: local
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fastboot-operator-role
rules:
  - apiGroups: ["io.platform.fastboot"]
    resources: ["platforms","databases"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods","services","secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fastboot-operator-binding
subjects:
  - kind: ServiceAccount
    name: fastboot-operator-sa
    namespace: local
roleRef:
  kind: ClusterRole
  name: fastboot-operator-role
  apiGroup: rbac.authorization.k8s.io