apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastboot-idp-operator
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastboot-idp-operator
  template:
    metadata:
      labels:
        app: fastboot-idp-operator
    spec:
      serviceAccountName: fastboot-operator-sa
      containers:
        - name: operator
          image: fastboot-idp-operator:local
          imagePullPolicy: Never