apiVersion: io.platform.fastboot/v1alpha1
kind: Platform
metadata:
  name: fastboot-idp
  namespace: local
spec:
  name: fastboot-idp
  stage: local
  version: 1.0.0
  services:
    databases:
      - name: postgres-db
        type: postgres
        version: "15"
        port: 5432
        secretName: postgres-secret