apiVersion: v2
name: fastboot-platform
description: A Helm chart for deploying the Spring Boot application called FastBoot Internal Developer Platform
type: application
version: 1.0.0
appVersion: "1.0.0"