appName: fastboot

artifactory:
  username: ""

rbac:
  serviceAccountName: fastboot-operator-sa
  clusterRoleName: fastboot-operator-role
  clusterRoleBindingName: ClusterRoleBinding

image:
  repository: fastboot-operator
  tag: local
  pullPolicy: Never
  imagePullSecret: artifactory-secret

deployment:
  name: fastboot-operator
  appName: fastboot-operator
  replicas: 1
  selectorLabel: fastboot-operator
  resources:
    requests:
      cpu: "100m"
      memory: "200Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  env:
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace

platform:
  name: fastboot-idp
  stage: local
  version: 1.0.0
  defaults:
    database:
      storageClass: local-path
      externalAccess: true
      sizes:
        SMALL:
          storage: 5Gi
          cpu: 250m
          memory: 512Mi
        MEDIUM:
          storage: 10Gi
          cpu: 500m
          memory: 1Gi
        LARGE:
          storage: 50Gi
          cpu: 1000m
          memory: 2Gi

platformServices:
  databases: []